name: Get follower list json

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0  # Specify your Python version

      - name: Install Dependencies
        run: pip install instaloader

      - name: Run Python Script
        env:
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_CSRF: ${{ secrets.INSTA_CSRF }}
          INSTA_SESSION: ${{ secrets.INSTA_SESSION }}
          TARGET_PAGE: ${{ secrets.TARGET_PAGE }}
        run: python get_followers.py


      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add followers.json
          git commit -m "Add followers list to main directory `date +'%Y-%m-%d %H:%M:%S'`"
          git push origin main
