name: Run Python Script

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - button-pressed

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0  # Specify your Python version

      - name: Install Dependencies
        run: pip install instaloader

      - name: Run Python Script
        env:
          INSTA_USERNAME: ${{ secrets.INSTA_USERNAME }}
          INSTA_PASSWORD: ${{ secrets.INSTA_PASSWORD }}
          INSTA_CSRF: ${{ secrets.INSTA_CSRF }}
          INSTA_SESSION: ${{ secrets.INSTA_SESSION }}
        run: python InstaAPI.py


      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Add generated file to main directory `date +'%Y-%m-%d %H:%M:%S'`"
          git push origin main
